name: 'ccache action'
description: 'Install ccache and handle caching from GH'
author: 'Yong Jian Ming'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'archive'
  color: 'blue'

# Define your inputs here.
inputs:
  path:
    description: 'Install ccache location. This is relative to github.workspace'
    required: false
    default: 'ccache'

  version:
    description:
      'Target ccache version to install. Follows the semver range specification'
    required: false
    default: '*'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
