name: Test Action

on:
  workflow_dispatch:

jobs:
  test_run:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ccache
        uses: ./
